### ISSUE TITLE
InternalServerError: 'NoneType' object has no attribute 'is_single'

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1594]
- EdgeDB Version: `1.0-alpha.4+g6df187d36.d20200716`
- OS Version: Docker

Steps to Reproduce:

Run this (not sure if this query makes sence, but it produces InternalServerError):
```edgeql
FOR x IN {<str>{} IF false ELSE <str>{'1'}}
UNION (SELECT x);
```

**Comment by Fogapod** [comment]
Not sure if this is related:
```
edgedb> SELECT {<str>{} IF true ELSE <str>{'1'}};
StreamErr {
    source: DecodeErr {
        source: Underflow {
            backtrace: Backtrace(
                   0:     0x564dd779da28 - <unknown>
                   1:     0x564dd797473c - <unknown>
                   2:     0x564dd7969563 - <unknown>
                   3:     0x564dd78f97b1 - <unknown>
                   4:     0x564dd789dc83 - <unknown>
                   5:     0x564dd7703895 - <unknown>
                   6:     0x564dd7760a33 - <unknown>
                   7:     0x564dd770dc1d - <unknown>
                   8:     0x564dd7828c0a - <unknown>
                   9:     0x564dd7a7aadb - <unknown>
                  10:     0x564dd7a7d397 - <unknown>
                  11:     0x564dd778680c - <unknown>
                  12:     0x564dd778cb0b - <unknown>
                  13:     0x564dd7aa8dfa - <unknown>
                  14:     0x7f5eec645fa3 - start_thread
                  15:     0x7f5eec55c4cf - clone
                  16:                0x0 - <unknown>
                ,
            ),
        },
    },
}
Reconnecting...
```

**Comment by elprans** [comment]
Both issues have been fixed. Thank you for the report!

**Comment by Fogapod** [comment]
Seems like it is only partially fixed:
```edgeql
edgedb> SELECT <str>{} IF true ELSE '';
{}
edgedb> FOR x IN {<str>{} IF false ELSE <str>{'1'}}
....... UNION (SELECT x);
{'1'}
edgedb> SELECT (
.......   FOR _ IN {{true} IF true ELSE <bool>{}}
.......   UNION (SELECT 1)
....... );
ERROR: InternalServerError: 'NoneType' object has no attribute 'is_single'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 83, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 60, in compile_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 116, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 590, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 136, in get_set_rvar
          return _process_toplevel_query(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 219, in _process_toplevel_query
          rvars = _get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 232, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 1073, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/stmt.py", line 69, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/clauses.py", line 112, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 83, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 112, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 590, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 181, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 232, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 1073, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/stmt.py", line 57, in compile_SelectStmt
          iterator_rvar = clauses.compile_iterator_expr(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/clauses.py", line 90, in compile_iterator_expr
          dispatch.visit(iterator_expr, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 83, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 112, in _compile_set_impl
          _compile_set(ir_set, ctx=scopectx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 590, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 181, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 232, in _get_set_rvar
          rvars = process_set_as_subquery(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 1073, in process_set_as_subquery
          dispatch.visit(ir_set.expr, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/dispatch.py", line 44, in visit
          compile(ir, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/stmt.py", line 69, in compile_SelectStmt
          outvar = clauses.compile_output(stmt.result, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/clauses.py", line 112, in compile_output
          dispatch.visit(ir_set, ctx=newctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 83, in visit_Set
          _compile_set_impl(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 116, in _compile_set_impl
          _compile_set(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 590, in _compile_set
          relgen.get_set_rvar(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 181, in get_set_rvar
          rvars = _get_set_rvar(ir_set, ctx=subctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 252, in _get_set_rvar
          rvars = process_set_as_ifelse(ir_set, stmt, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/relgen.py", line 1243, in process_set_as_ifelse
          if (if_expr_card.is_single() and else_expr_card.is_single()
      AttributeError: 'NoneType' object has no attribute 'is_single'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1683, in compile_eql_tokens
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1319, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1282, in _compile_dispatch_ql
          return self._compile_ql_query(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 614, in _compile_ql_query
          sql_text, argmap = pg_compiler.compile_ir_to_sql(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 105, in compile_ir_to_sql
          qtree = compile_ir_to_sql_tree(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 90, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: 'NoneType' object has no attribute 'is_single'
