### ISSUE TITLE
Inserting in fill_expr (and sometimes default) doesn't work

### ISSUE THREAD

**Issue by vonkoff** [edgedb/edgedb#3592]
- EdgeDB Version: EdgeDB CLI 1.1.0+8bc2c20
- OS Version: Mac OS Monterey version 12.1

Steps to Reproduce:

1. Updated default.esdl to include new table, Union_labor_name, and put in a link to that table into "Labor_union" table. 

```
Please specify an expression to populate existing objects in order to make link 'union_name' of object type 'default::Labor_union' required:
fill_expr> insert Union_labor_name { name:= "AAA" }
Created ./dbschema/migrations/00004.edgeql, id: m1f2ufyzoqfpfypfweuk5bwp2q7fuhuwgsvgq7rzsyqrdcove3pvlq
```

I did the following and then tried to edgedb migrate'and got the error:

```
edgedb migrate
edgedb error: UnsupportedBackendFeatureError: WITH clause containing a data-modifying statement must be at the top level 
I tried to just destroy the database and re-run it, but that didn't even work
edgedb instance destroy edgedb 
Do you really want to delete instance "edgedb"? (type Yes)
y
edgedb error: Canceled.
```

Schema:
```
  abstract type Named {
    required property name -> str {
      delegated constraint exclusive;
    }
  }
  type Labor_union {
    required link union_name -> Union_labor_name;
    link abbrev -> Abbreviation;

  } 
  type Union_labor_name extending Named {}
```

**Comment by colinhacks** [comment]
You have to type out `Yes` to delete the database, not just `y`. 

The first part (lack of support for `insert` in `fill_expr`) is still a bug per https://discord.com/channels/841451783728529451/849377751370432573/950859606865870919

**Comment by msullivan** [comment]
This is definitely doable though it will require some restructuring of how we emit code to do conversions.

I think we'll need to do something along the lines of:
1. Generate a CTE that computes the rows that need to be updated
2. Compile the `fill_expr` with that generated external CTE an external_rvar and an iterator_cte, or something like that
3. Pull the main body of the generated expression out as another CTE
4. Plumb all of that into the actual code to do the update

**Comment by msullivan** [comment]
On top of the fill_expr problem, this happens with defaults when a new link is added. The unfortunate bit here is that it *does* work to create a link with a default containing an `insert` as part of a new type, but not when altering it onto an existing type.

This is because https://github.com/edgedb/edgedb/pull/3750 makes adding a new link with a default use the `fill_expr` flow to populate the column with the default. (Previously it just incorrectly did *not* do that.)

**Comment by kunjee17** [comment]
Any update on this issue ? There are many PR merged mentioning this issue but issue it self is open.

**Comment by aljazerzen** [comment]
Yes, we've merged a few PRs but they are about reporting better errors when using mutation in `fill_expr` or in defaults. This issue is something I'm working on, but I cannot give you an ETA.

**Comment by obeavers** [comment]
@aljazerzen any update/progress here?

**Comment by aljazerzen** [comment]
It turns out that this is very close in implementation to the upcoming triggers (see RFCs repo), which I why I'm holding back on this.

I can say that this will be done in 3.0 (i.e. second part of February), but maybe I'll get around to it sooner.

**Comment by msullivan** [comment]
In progress in #4873

**Comment by msullivan** [comment]
Fixed by #4873

**Comment by kunjee17** [comment]
@msullivan is this published in latest version? Because I am still facing the same issue ? Or can you put it any example for same ?

**Comment by msullivan** [comment]
Yes, this should have gone out in 2.10. Can you give an example of what failed for you?

**Comment by kunjee17** [comment]
simple insert query as default. `(insert Item { name := 'name' })` in fill_expr .
